In [5]:
import numpy as np
from scipy import stats

### 단일표본 T-test

In [9]:
# 학생 키에 대한 리스트 구성 ( 랜덤 배치 )

height_list = np.random.randint(low=162, high=182, size=20)
height_list

array([167, 179, 169, 172, 180, 178, 178, 163, 169, 174, 163, 181, 167,
       178, 175, 165, 175, 167, 178, 179])

In [10]:
# T-test 수행

tTestResult = stats.ttest_1samp(height_list, 168)
tTestResult

Ttest_1sampResult(statistic=3.577130534210188, pvalue=0.002010349081274129)

In [13]:
# 결과 확인

print('t검정 통계량 = %.3f, pvalue = %.3f'%(tTestResult))
# pvalue가 0.05보다 작다 즉 유의성이있음으로 대립가설을 채택한다

t검정 통계량 = 3.577, pvalue = 0.002


### 독립표본 T-test

In [15]:
# 첫 번째 집단의 키 샘플링 하기

np.random.seed(1)
group1Heights = np.random.randint(low=157, high=178, size=20)
group1Heights

array([162, 168, 169, 165, 166, 168, 162, 172, 157, 173, 158, 169, 164,
       170, 163, 175, 177, 162, 175, 177])

In [16]:
# 두 번째 집단의 키 샘플링 하기

group2Heights = np.random.randint(low=162, high=182, size=20)
group2Heights

array([173, 172, 176, 180, 166, 171, 179, 162, 175, 171, 171, 169, 163,
       162, 179, 170, 175, 181, 177, 172])

In [17]:
# Case1 - 두 집단의 평균 키차이가 없다

tTestResult= stats.ttest_ind(group1Heights, group2Heights)
tTestResult

Ttest_indResult(statistic=-2.466231851659976, pvalue=0.01827995629176634)

In [19]:
# Case2 - 두 집단의 평균 키차이가 있다.

# 대립가설 (alternative값에 따라 group1Height와 group2Height가 어떻게 다른지에 대한 해석)
# two-sided : 단순히 같지 않다.
# less : group1Heights가 group2Heights보다 작다.
# greater: group1Heights가 group2Heights보다 크다.
tTestResult= stats.ttest_ind(group1Heights, group2Heights, alternative = "less")
tTestResult

Ttest_indResult(statistic=-2.466231851659976, pvalue=0.00913997814588317)

### 대응 표본 T-test

In [21]:
# 보조제 복용전 몸무게 랜덤 생성

# 복용전 몸무게에 대한 랜덤 값 배치
beforeWeights = np.random.randint(low=60, high=90, size=20)
beforeWeights

array([85, 68, 67, 63, 66, 81, 77, 85, 63, 64, 84, 77, 71, 72, 86, 80, 76,
       73, 79, 69])

In [23]:
# 보조제 복용 후 몸무게를 가정한 데이터 생성

# 복용 후 몸무게를 가정한 데이터 변조
tmp_list = []
for i in beforeWeights:
    tmp_list.append(i - np.random.normal(2, 0.02))
    
afterWeights = np.array(tmp_list)
afterWeights

array([82.98080726, 66.00254606, 64.98602892, 61.0445099 , 64.02536459,
       78.97215636, 74.96152336, 82.98017817, 60.99238778, 62.01495533,
       82.02635355, 74.9733418 , 69.0136908 , 69.97488035, 83.99006547,
       77.99341448, 74.0000238 , 71.00614585, 77.00367074, 67.0110595 ])

In [24]:
# Case1 - 복용 전후의 몸무게가 같은지 다른지 확인

tTestResult= stats.ttest_rel(beforeWeights, afterWeights)
tTestResult

Ttest_relResult(statistic=422.03198729685283, pvalue=3.334491000484102e-39)

In [25]:
# Case2 - 대립가설 : 복용전이 복용후 보다 크다

tTestResult= stats.ttest_rel(beforeWeights, afterWeights, alternative='greater')
tTestResult

Ttest_relResult(statistic=422.03198729685283, pvalue=1.667245500242051e-39)

In [26]:
# Case3 - 대립가설 : 복용 전의 몸무게가 복용후 보다 작다.

tTestResult= stats.ttest_rel(beforeWeights, afterWeights, alternative='less')
tTestResult

Ttest_relResult(statistic=422.03198729685283, pvalue=1.0)

### 독립 표본 T-test의 정규성과 등분산성

In [27]:
# 데이터 정의하기

nonsmokers = [18, 22, 21, 17, 20, 17, 23, 20, 22, 21]
smokers = [16, 20, 14, 21, 20, 18, 13, 15, 17, 21]

In [28]:
# 정규성 검정
# pvalue 값이 0.05보다 크면 정규성을 만족한다고 본다.

# 정규성 검정 (Shapiro-Wilk normality test)
normal1 = stats.shapiro(nonsmokers)
normal2 = stats.shapiro(smokers)
print(normal1)
print(normal2)

ShapiroResult(statistic=0.9119927883148193, pvalue=0.2949617803096771)
ShapiroResult(statistic=0.9194088578224182, pvalue=0.35205063223838806)


In [29]:
# 두 데이터의 등분산성 검정 ( Case1 )
# pvalue값이 0.05보다 크면 등분산성을 만족한다고 본다.

levene = stats.levene(nonsmokers, smokers)
levene

LeveneResult(statistic=1.945945945945946, pvalue=0.18000074963498305)

In [33]:
# 두 데이터의 등분산성 검정 ( Case2 )
# pvalue값이 0.05보다 크면 등분산성을 만족한다고 본다.

bartlett = stats.bartlett(nonsmokers, smokers)
bartlett

BartlettResult(statistic=0.8904487989220573, pvalue=0.3453557166446204)

In [34]:
# 독립표본 T-test 수행하기
# pvalue값이 0.05보다 크면 등분산성을 만족한다고 본다.

tTestResult = stats.ttest_ind(nonsmokers, smokers)
tTestResult

Ttest_indResult(statistic=2.2573164126756087, pvalue=0.036652255899794484)