### 균등 분포 난수

#### 균등 분포 난수 실험

In [1]:
import tensorflow as tf

In [2]:
# 스칼라 형태의 균등 분포 난수

uni_rnd1 = tf.random.uniform(shape=[], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd1)

65


In [3]:
# 벡터 형태의 균등 분포 난수

uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[18 19 57 90 47]


In [4]:
# 행렬 형태의 균등 분포 난수

uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[78 54 61]
 [53 10 9]]


In [5]:
# 텐서 형태의 균등 분포 난수

uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[26 22 48 61]
  [15 30 10 77]
  [84 80 20 19]]

 [[78 56 54 47]
  [67 27 9 60]
  [74 34 83 47]]]


#### 렌덤값을 갖는 행렬 곱 예시

In [6]:
# 랜덤값을 갖는 3행 2열의 행렬을 변수 x로 정의

x = tf.Variable(tf.random.uniform([3, 2]))
tf.print(x)

[[0.586903811 0.682119727]
 [0.834867358 0.203852296]
 [0.45000577 0.111027]]


In [7]:
# 랜덤값을 갖는 2행 1열의 행렬을 변수 Y로 정의

y = tf.Variable(tf.random.uniform([2, 1]))
tf.print(y)

[[0.191874981]
 [0.576822281]]


In [8]:
# 행렬 곱에 대한 연산을 수행하는 노드 정의

expr = tf.matmul(x, y)
tf.print(expr)

[[0.506074]
 [0.277776718]
 [0.150387704]]


### 정규 분포 난수

#### 정규 분포 난수 실험

In [9]:
# 스칼라 형태의 정규 분포 난수

normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

0.395558834


In [11]:
# 백터 형태의 정규 분포 난수

uni_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(uni_rnd2)

[0.0983955264 2.08599257 -0.446370572 -2.43472838 1.86212361]


In [12]:
# 행렬 형태의 정규 분포 난수

normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[0.353841603 0.0596389808 -0.330413043]
 [-0.0962914154 -0.0467515066 1.10548675]]


In [13]:
# 텐서 형태의 정규 분포 난수 

normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[-1.25358725 -1.68506444 0.80582875 -0.641347706]
  [0.680685103 -1.16534805 -1.14339781 0.25619185]
  [-1.23203421 -0.0185293183 0.212018415 -0.606983483]]

 [[-0.305503696 0.407026827 0.30483225 -0.175678656]
  [-0.505423367 -0.300732881 -0.782738 0.0146494666]
  [0.974697113 -0.902104676 -0.803190172 1.53655076]]]
