In [1]:
import tensorflow as tf

### 변수

In [3]:
# 암묵적 타입의 변수 생성하기

x = tf.Variable(123)
tf.print(x)

y = tf.Variable(x + 100)
tf.print(y)

123
223


In [4]:
# 명시적 타입의 변수 생성하기

x = tf.Variable(123, dtype=tf.float32)
tf.print(x)

123


### 텐서

#### 텐서 실험

In [5]:
import numpy as np

In [7]:
# 랭크가 0인 배열 -> 스칼라

a = 100
ts1 = np.array(a)
print(ts1.shape)
ts1

()


array(100)

In [8]:
# 랭크가 1인 배열 -> 벡터

b = [1, 2, 3]
ts2 = np.array(b)
print(ts2.shape)
ts2

(3,)


array([1, 2, 3])

In [9]:
# 랭크가 2인 배열 -> 행렬

c = [ [10, 20, 30], [100, 200, 300] ]
ts3 = np.array(c)
print(ts3.shape)
ts3

(2, 3)


array([[ 10,  20,  30],
       [100, 200, 300]])

In [10]:
# 랭크가 3인 배열 -> 텐서

d = [ [ [-1, -2, -3], [1, 2, 3] ], [ [-1, 0, 1], [1, 0, -1] ] ]
ts4 = np.array(d)
print(ts4.shape)
ts4

(2, 2, 3)


array([[[-1, -2, -3],
        [ 1,  2,  3]],

       [[-1,  0,  1],
        [ 1,  0, -1]]])

### 계산 그래프

In [11]:
# 명시적 타입을 갖는 노드 정의

node1 = tf.constant(3.0, dtype=tf.float32, name='hello')
print(node1)
tf.print(node1)

tf.Tensor(3.0, shape=(), dtype=float32)
3


In [12]:
# 암묵적 타입을 갖는 노드 정의

node2 = tf.constant(4.0, name='world')
print(node2)
tf.print(node2)

tf.Tensor(4.0, shape=(), dtype=float32)
4


In [14]:
# 두개의 노드의 값을 더하는 연산을 수행하는 node3를 정의

node3 = tf.add(node1, node2)
print(node3)
tf.print(node3)

tf.Tensor(7.0, shape=(), dtype=float32)
7
